### ISSUE TITLE
Error in the console: 'NoneType' object has no attribute 'project_data'

### ISSUE THREAD

**Issue by aziz** [tptee/FlowIDE#15]
```
Traceback (most recent call last):
  File "flowide.listeners.coverage in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 14, in <lambda>
  File "flowide.util in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 11, in wrapper
  File "flowide.util in /Users/allen/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 20, in debounced
AttributeError: 'NoneType' object has no attribute 'project_data'
```

**Comment by olegbl** [comment]
Seems to happen when opening the same file in two different panes. Both instances of the file are closed and error gets spit out.

**Comment by dantman** [comment]
Same, I get this over and over in a project that isn't using flow yet.
```

Traceback (most recent call last):
  File "flowide.listeners.coverage in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 14, in <lambda>
  File "flowide.util in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 11, in wrapper
  File "flowide.util in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 20, in debounced
AttributeError: 'NoneType' object has no attribute 'project_data'
Traceback (most recent call last):
  File "flowide.listeners.check in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 13, in <lambda>
  File "flowide.util in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 11, in wrapper
  File "flowide.util in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 20, in debounced
AttributeError: 'NoneType' object has no attribute 'project_data'
Traceback (most recent call last):
  File "flowide.listeners.coverage in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 14, in <lambda>
  File "flowide.util in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 11, in wrapper
  File "flowide.util in /Users/daniel/Library/Application Support/Sublime Text 3/Installed Packages/FlowIDE.sublime-package", line 20, in debounced
AttributeError: 'NoneType' object has no attribute 'project_data'
```

**Comment by sarayourfriend** [comment]
Is this issue being worked on at all?
